version: "3.8"

services:
  adminportal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adminportal
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./generated-pdfs:/app/generated-pdfs
